spring.application.name=photos-clone-api
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


spring.datasource.url=jdbc:h2:file:~/springboot;AUTO_SERVER=TRUE;
spring.sql.init.mode=always
spring.h2.console.enabled=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true


app.jwt.secret=${JWT_SECRET:VGhpc0lzQVRlc3RPbmx5SldUU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}

